### ISSUE TITLE
cdn always serves up compressed?

### ISSUE THREAD

**Issue by jots** [lovely-io/lovely.io-stl#75]
wget http://cdn.lovely.io/core.js

core.js is a gzipped version.  

should the cdn respect headers and serve ungzipped versions when client doesn't send Accept-Encoding: gzip  ?

**Comment by kaievns** [comment]
sorry, can't do that. the problem is that we're using cloudfront as a content delivery proxy and it freezes all the requests on their server nodes all across the world. so it's either all zipped or all unzipped.

but why do you wanna it unzipped? all browsers those days support gzip. and if you really wanna use wget for some reason, you always can pipe it with `| unzip`
